### ISSUE TITLE
what is best

### ISSUE THREAD

**Issue by jimmywarting** [Q42Philips/protobuf-vs-graphql#2]
don't understand the charts.

higher = better?
lower = better?
what dose the left side represent?

"A picture is worth a thousand words" - well, not in this case.
a readme update would be cool

**Comment by PiotrZakrzewski** [comment]
@EMLGaming ^^^

**Comment by dclipca** [comment]
Well, it seems gRPC is on average 0.4 msec per request while GraphQL is 4 msec per request so gRPC is on average 10 times faster.

**Comment by miguepiscy** [comment]
@jimmywarting  you should look at the x-axis, where the requests are concentrated

**Comment by EMLGaming** [comment]
The graphs are boxplots, the x-axis corresponds to the roundtrip speed taken for one request. The higher the plot the more requests had the same speed. Keeping this in mind ideal would be a very densly populated graph (meaning the round trip speed would be very consistent) as far left as possible (meaning the time is smallest). 

For a detailed explanation on this matter this blogpost should help https://blog.q42.nl/graphql-keep-alive-4379fe1a8b58/

I hope this properly awnsers your question and sorry for taking so long! Let me know if you would like any aditional information.

**Comment by hermanbanken** [comment]
I'm closing this repository & archiving it. We have settled on using Golang, Google Protobuf with gRPC.

Of course, it all depends on your use case. If you have high volumes of data picking the fastest transport becomes more important. If you are sending large or complex nested objects, this results in lots of extra data to be transferred/parsed. Using Google Protobuf potentially saves a lot of time on parsing & allocating memory. For example in Golang, it makes sense to use structs instead of pointers, to save time during the Garbage Collection phase. Also take a look at https://github.com/alecthomas/go_serialization_benchmarks#results.
